# Estrategias y ventajas competitivas {#chap8}

Un empresa posee ventaja competitiva cuando tiene cualquier característica que la hace diferente de las demás de forma que se sitúa en una posición privilegiada para competir. Solo se considerará ventaja competitiva aquellas que se traducen en mayor rentabilidad. Esto nos permite hacer una definición incluso más restrictiva de ventaja competitiva, que será aquella que se da cuando la diferencia entre el precio y el coste de producción (margen) es superior en una empresa respecto a las demás.

Naturalmente, para que la ventaja competitiva sea tal debe permanecer en el tiempo a pesar de los cambios que puedan darse en el entorno en el que opera la empresa. Esto depende de las barreras que pueda poner la empresa a la imitación, de la capacidad de las demás empresas para imitar la ventaja competitiva o de producir otras innovaciones que la anulen y del dinamismo de la industria que puede hacer que la vida de las innovaciones sea breve.

La estrategia debe ayudar a la empresa a conseguir y mantener en el tiempo las ventajas competitivas.

## Estrategias genéricas

Las estrategias genéricas se deben a Porter (1982) e inciden sobre el incremento de rentabilidad reduciendo costes mediante el **liderazgo en costes** o incrementando el precio por medio de la **diferenciación**. Existe una tercera vía que es la **segmentación de mercados**, consistente en enfocarse en un grupo de compradores, un tipo de productos o un mercado geográfico. En cada segmento aplicará el liderazgo de costes o la diferenciación del producto. En este sentido, la segmentación de mercados no es una estrategia independiente de las otras dos.

La experiencia práctica ha demostrado que buscar a la vez el liderazgo en costes y la diferenciación produce situaciones en las que las empresas no tienen éxito en ninguna de las dos estrategias, quedándose estancadas en el medio. Es por ello, que los expertos recomiendan decantarse por una de ellas exclusivamente.

### Liderazgo en costes

La ventaja en costes consiste en mantener costes inferiores a los de sus competidores para un producto o servicio semejante o comparable en calidad. La estrategia va dirigida a mantener o incluso ampliar esa diferencia en el tiempo. Esta estrategia se puede implantar en industrias donde el producto está estandarizado, la competencia en precios es intensa, hay poco margen para aplicar la diferenciación de producto y los clientes de las empresas tienen poder de negociación.

La ventaja en coste depende de muchos factores, como son la experiencia, la existencia de economías de escala, condiciones favorables de cualquier tipo por la localización de la empresa, poder de negociación con los proveedores, etc.

::: callout-tip
## Ejemplos

En [este enlace](https://anatrenza.com/liderazgo-en-costes/){target="_blank"} puedes consultar varios ejemplos de liderazgo en costes.
:::

### Diferenciación

La ventaja competitiva en diferenciación de productos se da cuando una empresa ofrece un producto o servicio comparable al de otras empresas, pero que tiene ciertas características que hace que los clientes lo perciban como único. Esto hace que los clientes estén dispuestos a pagar precios más altos. La empresa puede disfrutar de esta ventaja incluso aunque los costes unitarios sean superiores. La estrategia de diferenciación es posibles para productos con cierta sofisticación, los clientes son tales que les hacer percibir el producto como diferente o les sirve a ellos para diferenciarse socialmente, es difícil imitar las características diferentes, etc.

La estrategia de diferenciación puede darse por las características del producto en sí (propiedades físicas, servicios postventa, etc.), del mercado (moda, etc.), de la empresa (identidad, estilo, valores, etc.) o de otras variables (ética empresarial, responsabilidad social, etc.).

::: callout-tip
## Ejemplos

En [este enlace](https://anatrenza.com/estrategia-diferenciacion/#:~:text=Esta%20estrategia%20se%20basa%20en,tiene%20ninguno%20de%20sus%20competidores.){target="_blank"} puedes consultar varios ejemplos de estrategias de diferenciación.
:::

## Estrategias corporativas

Las estrategias corporativas se centran en analizar y decidir en qué mercados se va a operar. Se diferencian de las anteriores en que aquellas definen la forma en la que se opera para lograr los fines estratégicos.

Las empresas suelen buscar el crecimiento y desarrollo, que lo pueden conseguir mediante estrategias de **expansión** a nuevos productos o mercados o la **diversificación**, que implica expandirse en los dos sentido simultáneamente. Una estrategia especial de expansión que se considera aparte es la **integración vertical** que supone que la empresa asume fases del proceso productivo que realizaban otras empresas. Además puede buscar la consolidación adoptando estrategias de **reestructuración** eliminando partes del negocio que no funcionan y potenciando las que sí funcionan.

### Expansión

La estrategia de expansión pretende incrementar el volumen de negocio al que se dedica la empresa. Las principales estrategias de expansión son:

-   **Penetración en el mercado**: la empresa busca vender más a los clientes actuales o conseguir una base más amplia de clientes. Se puede conseguir con campañas publicitarias, promociones, etc. que tendrán un efecto a corto plazo y tenderán a desaparecer tan pronto desaparezca el estímulo, o se pueden utilizar las estrategias genéricas que, de implementarse con éxito, producirán un efecto más duradero.
-   **Desarrollo de productos**.
-   **Desarrollo de mercados**: búsqueda de nuevos segmentos de mercado, nuevas áreas geográficas o nuevas funciones para los productos existentes.

### Diversificación

Como ya se ha dicho más arriba, la estrategia de diversificación consiste en que la empresa se expande simultáneamente con nuevos productos y nuevos mercados. Toda esta novedad hace que la diversificación sea mucho más arriesgada que la mera expansión en entornos conocidos y de hecho puede exigir nuevos conocimientos, inversión en nuevas instalaciones, cambios en la organización, en la dirección, etc.

El mayor riesgo nos lleva a preguntarnos por las razones de tales estrategias, que pueden ser múltiples, como la reducción del riesgo global de la empresa, la saturación del mercado habitual, recursos sobrantes, aparición de sinergias, nuevas oportunidades de inversión, etc.

La diversificación puede ser de dos tipos. La diversificación **relacionada** se da cuando se comparten recursos entre las líneas de negocio antiguas y nuevas. La **no relacionada** se produce cuando la ruptura es completa y supone en realidad un inicio de cero de nuevas líneas de negocio, dando lugar habitualmente a conglomerados.

### Integración vertical

Una empresa que se integra verticalmente es aquella que asume actividades relacionadas con el ciclo completo de producción, por lo que la empresa se convierte en su propio proveedor (integración *aguas arriba*) o su propio cliente (integración *aguas abajo*).

Las razones para la integración vertical son muchas que podemos agrupar en dos categorías:

-   Reducción de costes: se aprovechan mejor los recursos, se simplifica el proceso productivo, se reducen existencias intermedias, se ingresan los márgenes de clientes y/o proveedores, se eliminan costes de transacción, etc.
-   Mejora de posición estratégica: se facilita el acceso de la empresa al suministro de factores y se garantiza la salida para sus productos, se pueden cambiar con más facilidad los precios, puede servir para crear barreras de entrada a los mercados y controlar mejor los mismos, etc.

Pero la integración vertical también conlleva riesgos. Aunque es cierto que la diversificación reduce el riesgo global, también lo puede aumentar al comprometer un volumen mayor de recursos, hacer más compleja la organización, etc. Además, al ser más grande se crea una barrera de salida, puede ser que el margen de proveedores o clientes no se asuma inmediatamente, etc.

### Reestructuración de cartera de negocios

Todo lo dicho hasta el momento da a entender que el desarrollo de la empresa está siempre en el crecimiento de la misma. Sin embargo, puede suceder también que para algunas empresas en determinados momentos le interese reducir su tamaño reestructurando su cartera de negocios, porque algunos de ellos tienen resultados negativos recurrentes, porque no encajan bien con el resto de la empresa o porque no se generan sinergias sino más bien todo lo contrario.

::: callout-tip
## Ejemplos

En [este enlace](https://blog.hubspot.es/marketing/desarrollo-de-mercado){target="_blank"} puedes encontrar múltiples ejemplos de estrategias corporativas.
:::

## Desarrollo interno y externo

El **desarrollo interno** o crecimiento orgánico o natural es el que se produce por inversiones de la propia empresa en sí misma de forma que incrementa su tamaño. Es la forma convencional, si bien desde hace tiempo se está imponiendo otras formas de crecimiento.

La posibilidad de crecimiento interno se suele expresar a través de la matriz de Ansoff de la @tbl-Ansoff, que relaciona las productos con los mercados, dando lugar a las distintas estrategias posibles.

| | **Productos actuales**    | **Productos nuevos** |
|:-|:-|:-|
| **Mercados actuales**| Penetración de mercado | Desarrollo de productos |
| **Mercados nuevos**  | Desarrollo de mercados | Diversificación         |
: Matriz de Ansoff {#tbl-Ansoff}

El **desarrollo externo** consiste en adquirir o buscar asociación o participación en otras empresas que ya están en funcionamiento.

Con el desarrollo externo se puede conseguir mayor eficiencia por la reducción de costes, adquisición de nuevos recursos, nuevos equipos directivos, nueva cultura empresarial, se colocan recursos excedentarios, se generan sinergias, etc.

Otro objetivo habitual para decantarse por el desarrollo externo es conseguir mayor poder de mercado. Mediante fusiones y adquisiciones de empresas en la misma etapa del ciclo productivo (**integración horizontal**) se reduce la competencia en el sector y se incrementa la rentabilidad futura esperada. Ante la globalización de los mercados las fusiones y adquisiciones de empresas internacionales pueden crear competidores internacionales de primer nivel.

Existen tres formas de desarrollo externo:

-   **Fusiones**: varias empresas se unen perdiendo todas ellas su forma jurídica original. Las fusiones pueden ser:
    -   **Puras**: cuando las empresas aportan todos sus recursos, patrimonio y deudas en la creación de la nueva empresa. Las empresas iniciales, que suelen ser de tamaños similares, se disuelven después de la fusión.
    -   **Por absorción**: cuando algunas empresas se integran en otra que no pierde su personalidad jurídica.
    -   **Con aportación parcial de activo**: cuando algunas empresas solo aportan una parte de su patrimonio a la sociedad nueva resultante de la fusión. se puede formar una empresa con personalidad jurídica nueva o se mantiene la de la empresa absorbente. No se disuelven las empresas absorbidas.
-   **Adquisiciones**: una empresa compra parte del capital de otras empresas con el fin de dominarla total o parcialmente. Ninguna empresa se disuelve en el proceso. El grado de control puede ser diverso. Se suele hablar de control absoluto cuando la matriz adquirente posee más del $80\%$ de la propiedad, mayoritario si posee más del $50\%$ y minoritario si posee menos del $50\%$ pero siendo el socio mayoritario. Se puede crear un **holding** con varias empresas filiales especializadas que están controladas por la matriz, aunque otra opción es permitir que una ***venture capital*** financie a otra empresa permitiéndole participar en el capital.
-   **Cooperación** entre empresas: son acuerdos entre empresas independientes para mejorar sus ventajas competitivas. Pueden adoptar distintas formas:
    -   **Cártel**: acuerdo tácito entre empresas para no competir en precios.
    -   **Cluster**: buscar nueva localización cerca de otra empresa.
    -   **Unión temporal de empresas** (UTE): unión de varias empresas en ocasiones puntuales.
    -   **Agrupación de interés económico** (AIE): asociación para rebajar precios.
    -   ***Joint-ventures***: acuerdo con otra empresa para vender en su mercado.
    -   **Franquicias**: permitir a otras empresas explotar nuestro modelo de negocio.
    -   ***Outsourcing***: se contrata a otra empresa para realizar parte de las tareas en lugar de realizarla por sí misma.

## Ventajas competitivas

Las ventajas competitivas son las características que hacen un producto, una marca o una empresa más atractivo sobre sus competidores, debido a que los clientes perciben un mayor valor en él. Dicha ventaja tiene que ser sostenida en el tiempo y tiene que redundar en mejores resultados que la competencia. Es evidente que para que se pueda mantener en el tiempo, la ventaja competitiva tiene que ser difícil de imitar. Las ventajas competitivas pueden deberse al producto en sí o a la forma cómo se gestiona su comercialización. Es decir, no basta con que el producto en sí tenga ventajas sobre sus competidores, los clientes y el público en general tienen que conocer que efectivamente esas ventajas existen y pueden beneficiarse de ellas.

Según Porter, "la ventaja competitiva crece fundamentalmente en razón del valor que una empresa es capaz de generar. El concepto de valor representa lo que los compradores están dispuestos a pagar, y el crecimiento de este valor a un nivel superior se debe a la capacidad de ofrecer precios más bajos en relación con los competidores por beneficios equivalentes o proporcionar beneficios únicos en el mercado que puedan compensar los precios más elevados".

Se suelen considerar cinco tipos de ventaja competitiva:

-   **Ventaja comparativa**: se trata de ofrecer el producto de mejor forma que la competencia. Cuando el producto es igual o muy parecido la única diferencia está en el cómo se ofrece. Aquí adquiere mucha importancia el precio, la presentación o la publicidad.
-   **Ventaja diferencial**: se busca características que hagan un producto o marca diferente y marcar dicha diferencia sistemáticamente. Sin lugar a dudas Apple es un buen ejemplo de esta estrategia.
-   **Ventaja competitiva sostenible**: se pretende que la ventaja competitiva se mantenga a largo plazo mediante estrategias destinadas a tal fin. Típicamente se trata de crear una marca con tanta fuerza que, aunque surjan competidores se seguirá percibiendo como algo exclusivo.

Los cuatro elementos típicos de la ventaja competitiva son:

-   **Precio**: reducir precios sin modificar calidad a base de reducir los costes de producción.
-   **Calidad**: incrementar la calidad sin modificar el precio, aunque éste no sea tan accesible. Es importante hacer visibles los destalles destacables del producto para que los clientes perciban de hecho la mejora de la calidad.
-   **Experiencia**: dar un trato personalizado a los clientes para incrementar su fidelización.
-   **Personalización y servicio**: conocer mejor a los clientes para ofrecerles mejores productos y servicios y sobre todo adaptados a sus necesidades concretas.

::: callout-tip
## Ejemplos

En [este enlace](https://blog.hubspot.es/marketing/ventaja-competitiva){target="_blank"} y en [este](https://robertoespinosa.es/2017/10/22/ventaja-competitiva-que-es-tipos-ejemplos/){target="_blank"} puedes encontrar casos reales de cómo las empresas explotan sus ventajas competitivas.
:::

## **Referencias** {.unnumbered}

Anatrenza (2023). Estrategia de liderazgo en costes. Recuperado el 18 de mayo de 2023. [Enlace](https://anatrenza.com/liderazgo-en-costes/){target="_blank"}.

Anatrenza (2023). Estrategia de diferenciación. Recuperado el 18 de mayo de 2023. [Enlace](https://anatrenza.com/estrategia-diferenciacion/#:~:text=Esta%20estrategia%20se%20basa%20en,tiene%20ninguno%20de%20sus%20competidores.){target="_blank"}.

Guerras Martín, L.A. y Navas, J.E. (2022), La dirección estratégica de la empresa. Teoría y aplicaciones, 6ª edición, Thomson Reuters.

Hubspot (2023). Los 8 mejores ejemplos de estrategias de desarrollo de mercado. Recuperado el 18 de mayo de 2023. [Enlace](https://blog.hubspot.es/marketing/desarrollo-de-mercado){target="_blank"}.

Hubspot (2023). Ventaja competitiva: qué es, características, tipos y ejemplos. Recuperado el 18 de mayo de 2023. [Enlace](https://blog.hubspot.es/marketing/ventaja-competitiva){target="_blank"}.

Porter, M. (1982). Estrategia Competitiva: Técnicas para el análisis de los sectores industriales y de la competencia, Grupo Editorial Patria S.A., Méjico.

Roberto Espinosa (2023). Ventaja Competitiva: qué es, claves, tipos y ejemplos. Recuperado el 18 de mayo de 2023. [Enlace](https://robertoespinosa.es/2017/10/22/ventaja-competitiva-que-es-tipos-ejemplos/){target="_blank"}.

Trapero, J.R., García, F.P., Pedregal, D.J. (2013), Dirección y Gestión Empresarial. Mcgraw-Hill. [Enlace](https://www.mheducation.es/direccion-y-gestion-empresarial-9788448190385-spain){target="_blank"}.
